#!/bin/sh
set -e

case "$1" in
    purge|remove|disappear)
        if which glib-compile-schemas >/dev/null 2>&1; then
            glib-compile-schemas /usr/share/glib-2.0/schemas || true
        fi

        if which update-desktop-database >/dev/null 2>&1; then
            update-desktop-database -q /usr/share/applications || true
        fi

        if which gtk-update-icon-cache >/dev/null 2>&1; then
            gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
        fi
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade)
        ;;
    *)
        ;;
esac

exit 0
