#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Convert Avro Keyboard 5 (Windows) .avrolayout files into the layout data
module of Avro Linux (src/avro-core/fixed/layoutdata.js).

Usage:
    scripts/import-avrolayout.py ID=FILE.avrolayout [ID=FILE.avrolayout ...] \
        > src/avro-core/fixed/layoutdata.js

The files of the layouts that ship with Avro Keyboard are in
https://github.com/mugli/Avro-Keyboard (assets/keyboard-layouts).
Only the key data and the layout credits are kept; the keyboard images are
dropped (the Layout Viewer draws the keyboard itself).
"""
import html
import json
import re
import sys

# Avro key names in keyboard order (VK_OEM_3 is the ` key, VK_OEM_PLUS the = key)
KEY_ORDER = (
    ['OEM3', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', 'MINUS', 'PLUS'] +
    list('QWERTYUIOP') + ['OEM4', 'OEM6', 'OEM5'] +
    list('ASDFGHJKL') + ['OEM1', 'OEM7'] +
    list('ZXCVBNM') + ['COMMA', 'PERIOD', 'OEM2']
)
STATES = ['Normal', 'Shift', 'AltGr', 'ShiftAltGr']
NUMPAD = ['Num0', 'Num1', 'Num2', 'Num3', 'Num4', 'Num5', 'Num6', 'Num7', 'Num8', 'Num9',
          'NumAdd', 'NumSubtract', 'NumMultiply', 'NumDivide', 'NumDecimal']

ELEMENT = re.compile(r'<(\w+)\s*>\s*<!\[CDATA\[(.*?)\]\]>\s*</\1>|<(\w+)\s*/>|<(\w+)\s*>\s*</\4>', re.S)


def js_string(s):
    out = json.dumps(s, ensure_ascii=False)
    # Invisible characters are written as escapes so they can be seen
    for ch in ('‌', '‍', ' '):
        out = out.replace(ch, '\\u%04x' % ord(ch))
    return out


def read_layout(path):
    with open(path, encoding='utf-8-sig') as f:
        xml = f.read()

    def meta(tag):
        m = re.search(r'<%s>\s*(?:<!\[CDATA\[(.*?)\]\]>)?\s*</%s>' % (tag, tag), xml, re.S)
        return html.unescape((m.group(1) or '').strip()) if m else ''

    version = meta('AvroKeyboardVersion') or re.search(r'<AvroKeyboardVersion>(.*?)</AvroKeyboardVersion>', xml).group(1)
    if version.strip() != '5':
        raise SystemExit('%s: not an Avro Keyboard 5 layout' % path)

    block = re.search(r'<KeyData>(.*?)</KeyData>', xml, re.S).group(1)
    data = {}
    for m in ELEMENT.finditer(block):
        if m.group(1):
            # Avro Keyboard HTML-decodes the CDATA text (TNetEncoding.HTML.Decode)
            data[m.group(1)] = html.unescape(m.group(2))
        else:
            data[m.group(3) or m.group(4)] = ''
    return {
        'name': meta('LayoutName'),
        'version': meta('LayoutVersion'),
        'developer': meta('DeveloperName'),
        'comment': meta('DeveloperComment'),
        'data': data,
    }


def main(args):
    if not args:
        raise SystemExit(__doc__)
    entries = []
    for arg in args:
        ident, _, path = arg.partition('=')
        if not path:
            raise SystemExit('expected ID=FILE, got %r' % arg)
        entries.append((ident, read_layout(path)))

    w = sys.stdout.write
    w('/*\n')
    w('    Avro Linux - Fixed keyboard layouts of Avro Keyboard 5\n')
    w('    SPDX-License-Identifier: MPL-2.0\n\n')
    w('    GENERATED by scripts/import-avrolayout.py; do not edit by hand.\n\n')
    w('    Source: the .avrolayout files of Avro Keyboard 5 for Windows\n')
    w('    (https://github.com/mugli/Avro-Keyboard, assets/keyboard-layouts),\n')
    w('    Mozilla Public License 2.0. The credits of each layout are kept below.\n\n')
    w("    keys:   Avro key name -> [Normal, Shift, AltGr, Shift+AltGr] ('' = nothing)\n")
    w('    numpad: Num0..Num9, NumAdd, NumSubtract, NumMultiply, NumDivide, NumDecimal\n')
    w('*/\n\n')
    w('var LAYOUTS = {\n')
    for n, (ident, lay) in enumerate(entries):
        d = lay['data']
        w('    %s: {\n' % js_string(ident))
        for field in ('name', 'version', 'developer', 'comment'):
            w('        %s: %s,\n' % (field, js_string(lay[field])))
        w('        keys: {\n')
        rows = []
        for key in KEY_ORDER:
            values = [d.get('Key_%s_%s' % (key, s), '') for s in STATES]
            if any(values):
                rows.append('            %s: [%s]' % (js_string(key), ', '.join(js_string(v) for v in values)))
        w(',\n'.join(rows) + '\n')
        w('        },\n')
        w('        numpad: {\n')
        rows = ['            %s: %s' % (js_string(k[3:]), js_string(d[k])) for k in NUMPAD if d.get(k, '')]
        w(',\n'.join(rows) + '\n')
        w('        }\n')
        w('    }%s\n' % (',' if n < len(entries) - 1 else ''))
    w('};\n\n')
    w('var LAYOUT_ORDER = [%s];\n' % ', '.join(js_string(i) for i, _ in entries))


if __name__ == '__main__':
    main(sys.argv[1:])
